FROM ruby:<%= @ruby_version %>-slim-buster
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN gem update --system && \
  gem install bundler:<%= @bundle_version %>
RUN bundle install
COPY . /myapp
